version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - ALIBABA_CLOUD_ACCESS_KEY_ID=
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET=
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped